stages:
  - test

variables:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  PYTHONUNBUFFERED: "1"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

default:
  image: python:3.13-slim
  tags: ["docker"]
  cache:
    - key:
        files:
          - requirements.txt
      paths:
        - .cache/pip/
        - .cache/huggingface/
    - key: "hf-cache-xlm-roberta-large"
      paths:
        - .cache/huggingface/
      policy: pull-push
  before_script:
    - python -V
    - pip install -U pip
    - pip install -r requirements.txt

test:
  stage: test
  script:
    - pip install pytest
    - pytest -s src/summary_test.py --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
    paths:
      - report.xml
      - data/experiments/base_scores-base_summarizer.csv
      - data/experiments/base_scores-missy_summarizer.csv