stages:
  - test

ragas_tests:
  stage: test
  image: python:3.13-slim
  tags: ["docker"]
  variables:
    PIP_DISABLE_PIP_VERSION_CHECK: "1"
    PYTHONDONTWRITEBYTECODE: "1"
    PYTHONUNBUFFERED: "1"
  before_script:
    - python -V
    - pip install -U pip
    - pip install -r requirements.txt
  script:
    - pytest -p src/summary_test.py --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
    paths:
      - report.xml